
export const SET_FRETBOARD = "SET_FRETBOARD";
export const ADD_FRETBOARD  = "ADD_FRETBOARD";
export const TOGGLE_NOTE = "TOGGLE_NOTE";
export const SET_CIRCLE_OF_FIFTHS_ROTATION = "SET_CIRCLE_OF_FIFTHS_ROTATION";
export const SET_DASHED_CIRCLE_ROTATION = "SET_DASHED_CIRCLE_ROTATION";
export const SET_PROGRESSION = "SET_PROGRESSION";
export const SET_PROGRESSION_KEY = "SET_PROGRESSION_KEY";
export const UPDATE_FRETBOARD_PROPERTY = 'UPDATE_FRETBOARD_PROPERTY';
