
export const SET_FRETBOARD = "SET_FRETBOARD";
export const ADD_FRETBOARD = "ADD_FRETBOARD";
export const TOGGLE_NOTE = "TOGGLE_NOTE";
export const SET_CIRCLE_OF_FIFTHS_ROTATION = "SET_CIRCLE_OF_FIFTHS_ROTATION";
export const SET_DASHED_CIRCLE_ROTATION = "SET_DASHED_CIRCLE_ROTATION";
export const SET_PROGRESSION = "SET_PROGRESSION";
export const SET_PROGRESSION_KEY = "SET_PROGRESSION_KEY";
export const UPDATE_FRETBOARD_PROPERTY = 'UPDATE_FRETBOARD_PROPERTY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';
